#!/usr/bin/env node
// status.mjs — regenerates the STATUS block in TODO.md from the facts themselves.
//
// WHY: build numbers, push state and suite counts used to be hand-typed in up to five
// files, and each copy rotted on its own schedule (the 16 Aug audit found tables 12
// builds stale presented as current). A generated number cannot disagree with itself.
//
// RUN: from this repo's folder, on the owner's machine or in a session:
//     node status.mjs
// Reads the sibling repos, runs READ-ONLY git (--no-optional-locks), counts suites,
// and best-effort fetches the live versions.json (5s timeout, cache-busted). Then
// rewrites ONLY the block between the STATUS markers in TODO.md.
//
// It never writes anything else, never runs a mutating git command, never deploys.

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const GH = join(here, '..');
const REPOS = {
  auction:  join(GH, 'vacation-kp.github.io'),
  schedule: join(GH, 'schedule'),
  tests:    join(GH, 'tests'),
  master:   here,
};

const buildOf = f => {
  try { return (readFileSync(f, 'utf8').match(/var\s+BUILD\s*=\s*(\d+)/) || [])[1] ?? '?'; }
  catch { return '?'; }
};
const jsonOf = f => { try { return JSON.parse(readFileSync(f, 'utf8')); } catch { return {}; } };
const git = (repo, args) => {
  try { return execSync(`git --no-optional-locks -C "${repo}" ${args}`, { encoding: 'utf8', timeout: 15000 }).trim(); }
  catch { return '(git unavailable)'; }
};
const dirty = repo => {
  const out = git(repo, 'status --short');
  if (out === '(git unavailable)') return out;
  const lines = out.split('\n').filter(Boolean);
  return lines.length ? `${lines.length} uncommitted file(s)` : 'clean';
};
const sync = repo => {
  const out = git(repo, 'status --short --branch');
  if (out.includes('ahead')) return 'AHEAD of origin — push pending';
  if (out.includes('behind')) return 'BEHIND origin';
  return 'in sync with origin';
};
const locks = repo => {
  try {
    const gd = join(repo, '.git');
    const found = [];
    for (const f of readdirSync(gd)) if (f.endsWith('.lock')) found.push(f);
    return found.length ? `⚠️ STALE LOCK: ${found.join(', ')}` : 'no locks';
  } catch { return '?'; }
};
const countSuites = (dir, pattern) => {
  try { return readdirSync(dir).filter(f => pattern.test(f)).length; } catch { return '?'; }
};

// --- gather ---------------------------------------------------------------
const now = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
const vJson = jsonOf(join(REPOS.auction, 'versions.json'));
const sJson = jsonOf(join(REPOS.schedule, 'versions.json'));
const disk = {
  aAdmin: buildOf(join(REPOS.auction, 'admin', 'index.html')),
  aStaff: buildOf(join(REPOS.auction, 'index.html')),
  sAdmin: buildOf(join(REPOS.schedule, 'admin', 'index.html')),
  sStaff: buildOf(join(REPOS.schedule, 'index.html')),
};
const auctionSuites = countSuites(REPOS.tests, /^test-.*\.mjs$/);
const schedSuites = countSuites(join(REPOS.tests, 'sched'), /-test\.mjs$/);

// live fetch, best effort
async function live(url) {
  try {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), 5000);
    const r = await fetch(url + '?cb=' + Date.now(), { signal: ctl.signal });
    clearTimeout(t);
    return await r.json();
  } catch { return null; }
}
const liveV = await live('https://anesthesia-kp.github.io/vacation/versions.json');
const liveS = await live('https://anesthesia-kp.github.io/schedule/versions.json');
// A null here means THIS MACHINE could not fetch, which on the owner's device is the
// normal case (the bridge VM has no outbound network). That is not a failed live check
// and must not read like one — say so plainly, and check live from the session instead.
const cmp = (livej, diskj) => livej === null ? 'not checked from here (no network) — fetch live separately'
  : JSON.stringify(livej) === JSON.stringify(diskj) ? 'live MATCHES disk'
  : `⚠️ LIVE DIFFERS FROM DISK — live says ${JSON.stringify(livej)} (just pushed? fetch again before trusting)`;

// --- render ---------------------------------------------------------------
const block = `<!-- STATUS:BEGIN — generated by status.mjs. DO NOT EDIT BY HAND. -->
**STATUS — generated ${now} by \`node status.mjs\`. Regenerate after every push.**

| | build (disk) | versions.json | live check |
|---|---|---|---|
| Auction admin / staff / mobile | ${disk.aAdmin} / ${disk.aStaff} / — | ${vJson.admin} / ${vJson.index} / ${vJson.mobile} | ${cmp(liveV, vJson)} |
| Schedule admin / staff | ${disk.sAdmin} / ${disk.sStaff} | ${sJson.admin} / ${sJson.index} | ${cmp(liveS, sJson)} |

| repo | working tree | vs origin | git locks |
|---|---|---|---|
| vacation-kp.github.io | ${dirty(REPOS.auction)} | ${sync(REPOS.auction)} | ${locks(REPOS.auction)} |
| schedule | ${dirty(REPOS.schedule)} | ${sync(REPOS.schedule)} | ${locks(REPOS.schedule)} |
| tests | ${dirty(REPOS.tests)} | ${sync(REPOS.tests)} | ${locks(REPOS.tests)} |
| anesthesia-kp.github.io | ${dirty(REPOS.master)} | ${sync(REPOS.master)} | ${locks(REPOS.master)} |

Suites on disk: auction **${auctionSuites}** (\`tests/test-*.mjs\`) · schedule **${schedSuites}**
(\`tests/sched/*-test.mjs\`). Assertion counts come from RUNNING the batteries, never from here.
<!-- STATUS:END -->`;

const todoPath = join(here, 'TODO.md');
const todo = readFileSync(todoPath, 'utf8');
const re = /<!-- STATUS:BEGIN[\s\S]*?<!-- STATUS:END -->/;
if (!re.test(todo)) { console.error('No STATUS markers in TODO.md — refusing to guess where to write.'); process.exit(1); }
writeFileSync(todoPath, todo.replace(re, block));
console.log(block.replace(/<!-- STATUS:(BEGIN|END)[^>]*-->/g, '').trim());
console.log('\nTODO.md STATUS block updated.');
